### ISSUE TITLE
`GET` endpoints aren't autogenerated

### ISSUE THREAD

**Issue by emcmanus** [dvcrn/ex_openai#15]
Many `GET` endpoints defined in `docs.yaml` aren't auto-generated.

For example get_assistant:

```yaml
  /assistants/{assistant_id}:
    get:
      operationId: getAssistant
      tags:
        - Assistants
      summary: Retrieves an assistant.
```

`ExOpenAI.Assistants.get_assistant` is not defined:

```
iex(5)> ExOpenAI.Assistants.
create_assistant/1         create_assistant/2         create_assistant_file/2    create_assistant_file/3    delete_assistant_file/2
delete_assistant_file/3    modify_assistant/1         modify_assistant/2
```

A non-exhaustive list of missing functions (maybe it provides some clues)
- list_fine_tunes
- list_assistants
- get_assisstant
- get_thread
- list_messages

Some `GET` endpoints are correctly defined, however. E.g.:
- list_models
- list_fine_tune_events
- retrieve_fine_tunes

Thank you! If you have any hints I'd be happy to drop in to the generator code and poke around.
